### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sunmin123456** [BJTUSensor/phi-OTDR-dataset-and-codes-#2]
def get_diff_data(data):  # 数据差分
    m = data.shape[0]  # 10000
    n = data.shape[1]  # 12
    data_diff = np.empty([m - 1, n]).astype(int)  # 9999,12
    for i in range(m - 1):
        data_diff[i, :] = data[i + 1, :].astype(float) - data[i, :].astype(float)
    return data_diff
def get_diff_data(data):  # 数据差分
    m = data.shape[0]  # 10000
    n = data.shape[1]  # 12
    data_diff = np.empty([m - 1, n]).astype(float)  # 9999,12
    for i in range(m - 1):
        data_diff[i, :] = data[i + 1, :].astype(float) - data[i, :].astype(float)
    return data_diff
int 类型的数据出现了数据越界，差分后的数据为负数，会加上65536后变为正数，这样得到的差分数据提取特征是没有什么效果的，改为float类型，重新训练后，SVM的准确率为0.878
![image](https://user-images.githubusercontent.com/40495190/226105673-a7a7ccdb-ca24-4311-b9bd-d56c311169ea.png)
![image](https://user-images.githubusercontent.com/40495190/226105685-75820308-223e-4401-ae00-0fab262f6e96.png)
![image](https://user-images.githubusercontent.com/40495190/226105710-0cf0a1d7-7a43-46b6-ad60-b8e9940c40d1.png)
![image](https://user-images.githubusercontent.com/40495190/226105720-a170cf91-ffe2-4695-9cdf-63f10936ebe1.png)

**Comment by LUOYEZHANYUE** [comment]
想咨询一个问题，相位敏感OTDR经过coupler接到PD上，再由PD接到示波器或者频谱仪上，怎么把转化成可以处理的SOR格式数据，大佬们可以说下嘛
